services:
  - type: web
    name: kunextgen-x-ai
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
